// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfwD5IxprVCply3ci5FxXl3TDi2JIQWto',
    appId: '1:664626781635:web:cb38f0f4c27d9670a5f176',
    messagingSenderId: '664626781635',
    projectId: 'flash-chat-371e2',
    authDomain: 'flash-chat-371e2.firebaseapp.com',
    storageBucket: 'flash-chat-371e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoV-Fr9-hLY64OEY-gTQXxqdHitXYaEdQ',
    appId: '1:664626781635:android:28623b3a3b67e6f5a5f176',
    messagingSenderId: '664626781635',
    projectId: 'flash-chat-371e2',
    storageBucket: 'flash-chat-371e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARvmqjw05IgQsLbxYtnZyh6jxEFgGCa9A',
    appId: '1:664626781635:ios:a79fdf27246c44a2a5f176',
    messagingSenderId: '664626781635',
    projectId: 'flash-chat-371e2',
    storageBucket: 'flash-chat-371e2.firebasestorage.app',
    iosBundleId: 'com.example.flutterBootcamp',
  );
}
